### ISSUE TITLE
watch more than one at a time with more accounts

### ISSUE THREAD

**Issue by josephisticated** [D3vl0per/Valorant-watcher#70]
can you make one that can watch with multiple accounts because you have more chance to drop like that

**Comment by SuperSandro2000** [comment]
Just duplicate the section in the docker-compose.yml for the second account.

**Comment by josephisticated** [comment]
lol dont know how to do that can you pls help :(

**Comment by SuperSandro2000** [comment]
```yaml
version: '3.5'
services:
  valorant-watcher1:
    #build: . #For local build
    #image: valorant-watcher:latest #For local build
    image: d3vm/valorant-watcher:latest
    restart: always
    environment:
      - token=first_token
  valorant-watcher2:
    #build: . #For local build
    #image: valorant-watcher:latest #For local build
    image: d3vm/valorant-watcher:latest
    restart: always
    environment:
      - token=2nd_token
```
